version: "3.9"

services:

  pgsqldb:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - pgsqldb_data:/var/lib/postgresql/data

  django-app:
    build: ./BackendAssignment
    command: 
      - /bin/bash 
      - -c 
      - |
        sleep 10
        python manage.py makemigrations
        python manage.py migrate
        gunicorn BackendAssignment.wsgi:application --bind 0.0.0.0:8000 --workers $APP_WORKERS
    volumes:
      - .:/BackendAssignment
    ports:
      - 8000:8000
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - APP_WORKERS=$APP_WORKERS
    depends_on:
      - pgsqldb
    restart: unless-stopped

volumes:
  pgsqldb_data:
