# Generated by Django 4.2.6 on 2023-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=250, unique=True)),
                ('full_name', models.CharField(max_length=250)),
            ],
        ),
    ]
