# Generated by Django 4.2.6 on 2023-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=250, unique=True)),
                ('pwd_hash', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
